#!/usr/bin/env node

const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
  	sendAll(message);
    console.log('received: %s', message);
  });
});

function sendAll(data){
	wss.clients.forEach(function each(client) {
		if (client.readyState === WebSocket.OPEN) {
			client.send(data);
		}
	});
};

// vim: set ft=javascript:
